# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170916_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='bought',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='economy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='full_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='schedule',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Subcategory'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='title_short',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
