# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170917_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='categoriesTotal',
            field=models.ManyToManyField(through='main.CounterTotal', to='main.Category'),
        ),
    ]
